Fix typo
rust-unofficial/patterns pull request #270
Opened 2021-08-24 16:58 UTC by poly000

2021-08-24 18:36 UTC, simonsan requested changes

2021-08-24 18:36 UTC, simonsan commented on functional/generics-type-classes.md
> +where new members can be added to object willy-nilly by any constructor.
"objects" in this case is right I guess, because it's plural

2021-08-24 18:36 UTC, simonsan commented on patterns/ffi/wrappers.md
> +into pointers. In Rust, a pointer means "the user manages the lifetime of the pointer."
Pointee is right here.

https://en.wiktionary.org/wiki/pointee

2021-08-24 18:38 UTC, simonsan commented
Hey, thanks for going through the files and correcting so many grammatic and spelling mistakes. I think those two instances up there don't need to be changed though. Can you please remove them and we are ready to merge. :)

2021-08-24 23:47 UTC, poly000 commented
> Hey, thanks for going through the files and correcting so many grammatic and spelling mistakes. I think those two instances up there don't need to be changed though. Can you please remove them and we are ready to merge. :)

ok

2021-08-25 02:42 UTC, simonsan approved these changes

2021-08-25 02:43 UTC, merged

2021-08-25 02:43 UTC, simonsan commented
@poly000 Thank you!