Update strategy.md
rust-unofficial/patterns pull request #379
Opened 2023-11-23 16:15 UTC by gdennie

I found the explanation of Strategy and Dependency injection near the top of the file confusing. After some additional reading elsewhere I thought this might be a bit clearer.

2023-11-23 17:41 UTC, neithernut requested changes
Disclaimer: not a maintainer.

I do feel at least some of these changes are an improvement. But the writing does come across not as fluid as it could be.

2023-11-23 17:41 UTC, neithernut commented on src/patterns/behavioural/strategy.md
> +The basic idea behind the Strategy pattern is actually the fundamental idea traits.
```suggestion
The basic idea behind the Strategy pattern is actually the fundamental idea of traits.
```

2023-11-23 17:41 UTC, neithernut commented on src/patterns/behavioural/strategy.md
> +but have parts whose actual implementation is left abstract or overridable
This sentence doesn't read that nice. But the meaning does come across.

2023-11-23 17:41 UTC, neithernut commented on src/patterns/behavioural/strategy.md
> +This is why we call it "Dependency Inversion".
This whole paragraph reads more convoluted than necessary.

2023-11-23 17:41 UTC, neithernut commented on src/patterns/behavioural/strategy.md
> +or algorithm invocation requirements, i.e., `Formatter` and `format(...)`.
This rewrite feels unnecessary.

2023-11-23 21:11 UTC, closed without merging

2023-12-11 22:31 UTC, MarcoIeni commented
Hey George, I'm sorry to see you closed this PR after Julian's feedback.
Is it because you didn't have the time to work on it?

2023-12-12 09:12 UTC, gdennie commented
yes, unfortunately.